config/routes.rb
Rails.application.routes.draw do
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :author, length: {minimum: 4}
  validates :content, length: {in: 4..280}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/controllers/tweets_controller.rb
require 'json'
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy like]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "!Tweet was successfully created." }
        format.json { render :index, status: :created, location: @tweet }
        if not session[:created_ids].nil?
          session[:created_ids].push(@tweet.id)
        else
          session[:created_ids] = [@tweet.id]
        end
      else
        if !@tweet.errors['author'][0].nil? and @tweet.errors['content'][0].nil?
          format.html { redirect_to root_path, notice: "Author " + @tweet.errors['author'][0]}
        elsif @tweet.errors['author'][0].nil? and !@tweet.errors['content'][0].nil?
          format.html { redirect_to root_path, notice: "Content " + @tweet.errors['content'][0] }
        else
          format.html { redirect_to root_path, notice: "Author " + @tweet.errors['author'][0] + " and Content " + @tweet.errors['content'][0]}
        end
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to root_path, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    if session[:created_ids].nil? || !session[:created_ids].include?(@tweet.id)
       respond_to do |format|
         format.html { redirect_to root_path, notice: "You are not allowed to delete this tweet." }
         format.json { head :forbidden }
       end
    else
      @tweet.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: "!Tweet was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end
  
  def like
    if session[:liked_ids].nil? || !session[:liked_ids].include?(@tweet.id)
      @tweet.likes += 1
      if not session[:liked_ids].nil?
        session[:liked_ids].push(@tweet.id)
      else
        session[:liked_ids] = [@tweet.id]
      end
    else
      @tweet.likes -= 1
      session[:liked_ids].delete(@tweet.id)
    end
    @tweet.save
    respond_to do |format|
        format.html{redirect_to root_path}
        format.json{head :no_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Name:</strong>
    <%= person.name %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <table border=0 cellpadding=2>
    <tr>
      <td>
        Your name:
      </td>
      <td>
        <input size="70" type="text" name="tweet[author]" id="tweet_author" />
      </td>
      <td/>
    </tr>
    <tr>
      <td>
        Your tweet:
      </td>
      <td>
        <textarea rows="2" cols="70" name="tweet[content]" id="tweet_content"></textarea>
      </td>
      <td>
        <input type="submit" name="commit" value="Tweet!" data-disable-with="Tweet!" />
      </td>
    </tr>
  </table>
<% end %>

app/views/tweets/_tweet.html.erb
  <div class="wotitem" id=tweet.id>
      <div class="likes">
        <span class="numlikes" id="showLikes_<%= tweet.id %>">
      	  <%= tweet.likes %>
        </span>
        <br/>
        <span class="smallfont">
     	  people like this
        <span>
        <br/>
        <h3>
          <% if session[:created_ids].nil? || !session[:created_ids].include?(tweet.id)%>
            <br/>
              <%= button_to 'Like', like_tweet_path(tweet), method: :put %>
          <% else %>
            <p class="destroy" >
              <%= button_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
            </p>
          <% end %>
        </h3>
      </div>
      <div class="item">
        <h4>
          <em>
    	  	<%=  tweet.author %>
          </em>
      	   @
      	   <%= tweet.created_at.strftime("%H:%m") %> 
        </h4>
        <p>
    	   <%=  tweet.content %>
        </p>
    </div>
  </div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag "wot.css" %>
<html>
<head>
    <title>Waslab04</title>
</head>

<body class="wotbody">
  <h1 class="wottitle">Wall of Tweets</h1>
  <br/>
  <div class="walltweet">
    <%= render 'form', tweet: @tweet %>
  </div>
  <br/>
  
  <% if notice %>
    <br>
    <div class="wotitem" id="notice">
      <% if notice[0] != "!" %>
        <span style="color: red;">
      	  <%= notice %>
        </span>
      <% else %>
        <span style="color: green;">
          <% notice.slice!(0) %>
        	<%= notice %>
        </span>
      <% end %>
    </div>
  <% end %>
  
  <br>
  <div>
    <% @actual_day = "" %>
    <% @tweets.each do |tweet| %>
      <% @tweeet_day = tweet.created_at.strftime("%A, %B %d, %Y") %>
      <% if @tweeet_day != @actual_day %>
        <h3>
  	      ......
  	      <%= @actual_day = @tweeet_day %>
        </h3>
      <% end %>
      <%= render tweet %>
    <% end %>
  </div>
</body>
</html>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>